# -*- coding: utf-8 -*-
"""skeletal_variation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jn_5IbhQ2BaZF2VgnNs6Imv0abl5_LYc

**Skeletal Variation** -


The comparison of skeletons across species lead to historical insights in evolutionary biology. In this project, you will explore the bones of the human body and make comparisons to a wide variety of mammals and birds.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
#mammal-neck-bones
df_mammal= pd.read_csv("/content/drive/MyDrive/DataScienceProjects/skeletal_variation/mammal-neck-bones.csv")
df_mammal

#bird-neck-bones
df_bird= pd.read_csv("/content/drive/MyDrive/DataScienceProjects/skeletal_variation/bird-neck-bones.csv")
df_bird

#human-neck-bones
df_human= pd.read_csv("/content/drive/MyDrive/DataScienceProjects/skeletal_variation/adult-human-skeleton.csv")
df_human

df_human['region'].value_counts()

"""Infants have more bones than adults, but as the baby develops, groups of bones fuse together. This is detailed in the 'fused_from' column of our data.

sort_values() using the fused_form column
"""

df_human.sort_values(by='fused_from', ascending=False)

print(df_human['fused_from'].sum())

"""Infants have more bone than adult."""

print(df_human.query('region == "neck"'))

import matplotlib.pyplot as plt

# Count of bones by region
df_human['region'].value_counts().plot(kind='bar', figsize=(8,5), title="Bone Counts by Region")
plt.show()

# Count of bones by subregion
df_human['subregion'].value_counts().plot(kind='barh', figsize=(8,5), title="Bone Counts by Subregion")
plt.show()

# Pie chart of side
df_human['side'].value_counts().plot(kind='pie', autopct='%1.1f%%', figsize=(6,6), title="Bones by Side")
plt.ylabel('')
plt.show()

# Scatter plot: fused_from vs index
df_human.reset_index().plot.scatter(x='index', y='fused_from', figsize=(8,5), title="Fused_from across Bones")
plt.show()

df_mammal.head(10)

df_mammal.query('species == "cheetah"')

df_mammal.query('neck_vertebrae !=7 ')

"""Aha! It looks like the only mammals without 7 vertebrae are manatees and sloths."""

df_bird

bird_counts = df_bird['neck_vertebrae'].value_counts()
bird_counts = bird_counts.sort_index()
bird_counts.plot.bar()

df_bird.query('neck_vertebrae == neck_vertebrae.max()')

